# Generated by Django 3.1.1 on 2020-09-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(blank=True, max_length=10, null=True, verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='MagSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.TextField(blank=True, max_length=20, null=True, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='Аватар')),
                ('skype', models.TextField(blank=True, max_length=50, null=True, verbose_name='Скайп')),
                ('zoom', models.TextField(blank=True, max_length=50, null=True, verbose_name='Зум')),
                ('telegram', models.TextField(blank=True, max_length=50, null=True, verbose_name='Телеграм')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.maggroup')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.magspecialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
